export type Region = 'asia' | 'europe' | 'africa' | 'americas' | 'oceania';

export const regionLabels: Record<Region, { ja: string; en: string }> = {
  asia: { ja: 'アジア', en: 'Asia' },
  europe: { ja: 'ヨーロッパ', en: 'Europe' },
  africa: { ja: 'アフリカ', en: 'Africa' },
  americas: { ja: '南北アメリカ', en: 'Americas' },
  oceania: { ja: 'オセアニア', en: 'Oceania' },
};

// ISO 3166-1 alpha-2 mapping to regions
export const countryRegionMap: Record<string, Region> = {
  // Asia
  // East Asia
  JP: 'asia',
  CN: 'asia',
  KR: 'asia',
  KP: 'asia',
  MN: 'asia',
  TW: 'asia',

  // Southeast Asia
  ID: 'asia',
  VN: 'asia',
  TH: 'asia',
  MY: 'asia',
  PH: 'asia',
  SG: 'asia',
  MM: 'asia',
  KH: 'asia',
  LA: 'asia',
  BN: 'asia',
  TL: 'asia',

  // South Asia
  IN: 'asia',
  PK: 'asia',
  BD: 'asia',
  LK: 'asia',
  NP: 'asia',
  AF: 'asia',
  BT: 'asia',
  MV: 'asia',

  // Central Asia
  KZ: 'asia',
  UZ: 'asia',
  TM: 'asia',
  KG: 'asia',
  TJ: 'asia',

  // Middle East
  SA: 'asia',
  IR: 'asia',
  TR: 'asia',
  IQ: 'asia',
  IL: 'asia',
  AE: 'asia',
  SY: 'asia',
  JO: 'asia',
  LB: 'asia',
  OM: 'asia',
  KW: 'asia',
  QA: 'asia',
  BH: 'asia',
  YE: 'asia',

  // Europe
  GB: 'europe',
  FR: 'europe',
  DE: 'europe',
  IT: 'europe',
  ES: 'europe',
  RU: 'europe',
  UA: 'europe',
  PL: 'europe',
  RO: 'europe',
  NL: 'europe',
  BE: 'europe',
  GR: 'europe',
  PT: 'europe',
  CZ: 'europe',
  HU: 'europe',
  SE: 'europe',
  AT: 'europe',
  CH: 'europe',
  BG: 'europe',
  DK: 'europe',
  FI: 'europe',
  SK: 'europe',
  NO: 'europe',
  IE: 'europe',
  HR: 'europe',
  MD: 'europe',
  BA: 'europe',
  AL: 'europe',
  LT: 'europe',
  MK: 'europe',
  SI: 'europe',
  LV: 'europe',
  EE: 'europe',
  ME: 'europe',
  LU: 'europe',
  MT: 'europe',
  IS: 'europe',
  AD: 'europe',
  MC: 'europe',
  LI: 'europe',
  SM: 'europe',
  VA: 'europe',
  BY: 'europe',
  RS: 'europe',
  GE: 'europe',
  AM: 'europe',
  AZ: 'europe',
  CY: 'europe',

  // Africa
  EG: 'africa',
  ZA: 'africa',
  NG: 'africa',
  KE: 'africa',
  ET: 'africa',
  TZ: 'africa',
  UG: 'africa',
  DZ: 'africa',
  SD: 'africa',
  MA: 'africa',
  AO: 'africa',
  MZ: 'africa',
  GH: 'africa',
  MG: 'africa',
  CM: 'africa',
  CI: 'africa',
  NE: 'africa',
  BF: 'africa',
  ML: 'africa',
  MW: 'africa',
  ZM: 'africa',
  SN: 'africa',
  TD: 'africa',
  SO: 'africa',
  ZW: 'africa',
  GN: 'africa',
  RW: 'africa',
  BJ: 'africa',
  BI: 'africa',
  TN: 'africa',
  SS: 'africa',
  TG: 'africa',
  SL: 'africa',
  LY: 'africa',
  CG: 'africa',
  LR: 'africa',
  CF: 'africa',
  MR: 'africa',
  ER: 'africa',
  NA: 'africa',
  GM: 'africa',
  BW: 'africa',
  GA: 'africa',
  LS: 'africa',
  GW: 'africa',
  GQ: 'africa',
  MU: 'africa',
  SZ: 'africa',
  DJ: 'africa',
  KM: 'africa',
  CV: 'africa',
  ST: 'africa',
  SC: 'africa',

  // Americas
  // North America (including Central America & Caribbean)
  US: 'americas',
  CA: 'americas',
  MX: 'americas',
  GT: 'americas',
  CU: 'americas',
  HT: 'americas',
  DO: 'americas',
  HN: 'americas',
  SV: 'americas',
  NI: 'americas',
  CR: 'americas',
  PA: 'americas',
  JM: 'americas',
  TT: 'americas',
  BS: 'americas',
  BZ: 'americas',
  BB: 'americas',
  LC: 'americas',
  GD: 'americas',
  VC: 'americas',
  AG: 'americas',
  DM: 'americas',
  KN: 'americas',

  // South America
  BR: 'americas',
  CO: 'americas',
  AR: 'americas',
  PE: 'americas',
  VE: 'americas',
  CL: 'americas',
  EC: 'americas',
  BO: 'americas',
  PY: 'americas',
  UY: 'americas',
  GY: 'americas',
  SR: 'americas',

  // Oceania
  AU: 'oceania',
  NZ: 'oceania',
  PG: 'oceania',
  FJ: 'oceania',
  SB: 'oceania',
  VU: 'oceania',
  WS: 'oceania',
  KI: 'oceania',
  TO: 'oceania',
  FM: 'oceania',
  PW: 'oceania',
  MH: 'oceania',
  TV: 'oceania',
  NR: 'oceania',
};
