export type Region =
  | 'east_asia'
  | 'southeast_asia'
  | 'south_asia'
  | 'central_asia'
  | 'middle_east'
  | 'europe'
  | 'africa'
  | 'north_america'
  | 'south_america'
  | 'oceania';

export const regionLabels: Record<Region, { ja: string; en: string }> = {
  east_asia: { ja: '東アジア', en: 'East Asia' },
  southeast_asia: { ja: '東南アジア', en: 'Southeast Asia' },
  south_asia: { ja: '南アジア', en: 'South Asia' },
  central_asia: { ja: '中央アジア', en: 'Central Asia' },
  middle_east: { ja: '中東', en: 'Middle East' },
  europe: { ja: 'ヨーロッパ', en: 'Europe' },
  africa: { ja: 'アフリカ', en: 'Africa' },
  north_america: { ja: '北米', en: 'North America' },
  south_america: { ja: '南米', en: 'South America' },
  oceania: { ja: 'オセアニア', en: 'Oceania' },
};

// ISO 3166-1 alpha-2 mapping to regions
export const countryRegionMap: Record<string, Region> = {
  // East Asia
  JP: 'east_asia',
  CN: 'east_asia',
  KR: 'east_asia',
  KP: 'east_asia',
  MN: 'east_asia',
  TW: 'east_asia',

  // Southeast Asia
  ID: 'southeast_asia',
  VN: 'southeast_asia',
  TH: 'southeast_asia',
  MY: 'southeast_asia',
  PH: 'southeast_asia',
  SG: 'southeast_asia',
  MM: 'southeast_asia',
  KH: 'southeast_asia',
  LA: 'southeast_asia',
  BN: 'southeast_asia',
  TL: 'southeast_asia',

  // South Asia
  IN: 'south_asia',
  PK: 'south_asia',
  BD: 'south_asia',
  LK: 'south_asia',
  NP: 'south_asia',
  AF: 'south_asia',
  BT: 'south_asia',
  MV: 'south_asia',

  // Central Asia
  KZ: 'central_asia',
  UZ: 'central_asia',
  TM: 'central_asia',
  KG: 'central_asia',
  TJ: 'central_asia',

  // Middle East
  SA: 'middle_east',
  IR: 'middle_east',
  TR: 'middle_east',
  IQ: 'middle_east',
  IL: 'middle_east',
  AE: 'middle_east',
  SY: 'middle_east',
  JO: 'middle_east',
  LB: 'middle_east',
  OM: 'middle_east',
  KW: 'middle_east',
  QA: 'middle_east',
  BH: 'middle_east',
  YE: 'middle_east',

  // Europe
  GB: 'europe',
  FR: 'europe',
  DE: 'europe',
  IT: 'europe',
  ES: 'europe',
  RU: 'europe',
  UA: 'europe',
  PL: 'europe',
  RO: 'europe',
  NL: 'europe',
  BE: 'europe',
  GR: 'europe',
  PT: 'europe',
  CZ: 'europe',
  HU: 'europe',
  SE: 'europe',
  AT: 'europe',
  CH: 'europe',
  BG: 'europe',
  DK: 'europe',
  FI: 'europe',
  SK: 'europe',
  NO: 'europe',
  IE: 'europe',
  HR: 'europe',
  MD: 'europe',
  BA: 'europe',
  AL: 'europe',
  LT: 'europe',
  MK: 'europe',
  SI: 'europe',
  LV: 'europe',
  EE: 'europe',
  ME: 'europe',
  LU: 'europe',
  MT: 'europe',
  IS: 'europe',
  AD: 'europe',
  MC: 'europe',
  LI: 'europe',
  SM: 'europe',
  VA: 'europe',
  BY: 'europe',
  RS: 'europe',
  GE: 'europe',
  AM: 'europe',
  AZ: 'europe',
  CY: 'europe',

  // Africa
  EG: 'africa',
  ZA: 'africa',
  NG: 'africa',
  KE: 'africa',
  ET: 'africa',
  TZ: 'africa',
  UG: 'africa',
  DZ: 'africa',
  SD: 'africa',
  MA: 'africa',
  AO: 'africa',
  MZ: 'africa',
  GH: 'africa',
  MG: 'africa',
  CM: 'africa',
  CI: 'africa',
  NE: 'africa',
  BF: 'africa',
  ML: 'africa',
  MW: 'africa',
  ZM: 'africa',
  SN: 'africa',
  TD: 'africa',
  SO: 'africa',
  ZW: 'africa',
  GN: 'africa',
  RW: 'africa',
  BJ: 'africa',
  BI: 'africa',
  TN: 'africa',
  SS: 'africa',
  TG: 'africa',
  SL: 'africa',
  LY: 'africa',
  CG: 'africa',
  LR: 'africa',
  CF: 'africa',
  MR: 'africa',
  ER: 'africa',
  NA: 'africa',
  GM: 'africa',
  BW: 'africa',
  GA: 'africa',
  LS: 'africa',
  GW: 'africa',
  GQ: 'africa',
  MU: 'africa',
  SZ: 'africa',
  DJ: 'africa',
  KM: 'africa',
  CV: 'africa',
  ST: 'africa',
  SC: 'africa',

  // North America (including Central America & Caribbean)
  US: 'north_america',
  CA: 'north_america',
  MX: 'north_america',
  GT: 'north_america',
  CU: 'north_america',
  HT: 'north_america',
  DO: 'north_america',
  HN: 'north_america',
  PY: 'north_america',
  SV: 'north_america',
  NI: 'north_america',
  CR: 'north_america',
  PA: 'north_america',
  JM: 'north_america',
  TT: 'north_america',
  BS: 'north_america',
  BZ: 'north_america',
  BB: 'north_america',
  LC: 'north_america',
  GD: 'north_america',
  VC: 'north_america',
  AG: 'north_america',
  DM: 'north_america',
  KN: 'north_america',

  // South America
  BR: 'south_america',
  CO: 'south_america',
  AR: 'south_america',
  PE: 'south_america',
  VE: 'south_america',
  CL: 'south_america',
  EC: 'south_america',
  BO: 'south_america',
  UY: 'south_america',
  GY: 'south_america',
  SR: 'south_america',

  // Oceania
  AU: 'oceania',
  NZ: 'oceania',
  PG: 'oceania',
  FJ: 'oceania',
  SB: 'oceania',
  VU: 'oceania',
  WS: 'oceania',
  KI: 'oceania',
  TO: 'oceania',
  FM: 'oceania',
  PW: 'oceania',
  MH: 'oceania',
  TV: 'oceania',
  NR: 'oceania',
};
